### ISSUE TITLE
Installation instructions did not work

### ISSUE THREAD

**Issue by HQ1791** [jdlrobson/MediaWikiWordpressThemes#2]
I am using Mediawiki 1.39.5 and i have downloaded MediaWikiWordpressThemes and followed the provided instructions. However, when i add the extensions into LocalSetting.php. It breaks my whole wiki. I need help to make these skin extensions work. Thanks!

**Comment by jdlrobson** [comment]
Hey, the current master supports the latest MediaWiki version.
For older releases you can try checking out one of the old branches, sounds like you need https://github.com/jdlrobson/MediaWikiWordpressThemes/releases/tag/REL1_39

Let me know if that doesn't work.

**Comment by HQ1791** [comment]
Hi, this branch also did not worked for me. I downloaded this branch and put it inside the MediaWiki skin folder. Then i go inside the MediaWikiWordpressThemes folder and run this command `ln -s MediaWikiWordpressThemes/* .` Then i add the wordpress skins into my LocalSettings.php file. But still it did not work. I don't know if i am missing something or doing something wrong. Thanks!

**Comment by HQ1791** [comment]
Hi, thank you for the quick response. This branch works for me.
