### ISSUE TITLE
Add my Wordpress Theme?

### ISSUE THREAD

**Issue by AdmiralJuicy** [jdlrobson/MediaWikiWordpressThemes#4]
Hello!

I was wondering if you could port my wiki theme to Mediawiki? It's using OceanWP.

Here's the link: https://sonic-city.net

Please let me know if this is something you can do, if not, I'll continue learning :)

Thanks again

**Comment by jdlrobson** [comment]
The Oceanwp theme was already ported. Please follow the install instructions on https://www.mediawiki.org/wiki/Skin:Oceanwp

(I don't provide any support for actually setting up the theme but you can ask questions at https://www.mediawiki.org/wiki/Project:Support_desk if you get stuck! Good luck!)
